---

image: registry.gitlab.com/fluidsignal/asserts:base

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker login registry.gitlab.com -u $DOCKER_USER -p $DOCKER_PASS
  - docker build --cache-from registry.gitlab.com/fluidsignal/asserts:base -f Dockerfile.base -t registry.gitlab.com/fluidsignal/asserts:base .


stages:
  - build
  - test
  - deploy
  - postdeploy

build:
    stage: build
    script:
        - docker build --cache-from registry.gitlab.com/fluidsignal/asserts:builder -f Dockerfile.builder -t registry.gitlab.com/fluidsignal/asserts:builder .
        - docker build --no-cache --build-arg gituser=$DOCKER_USER --build-arg gitpass=$DOCKER_PASS --build-arg branch=$CI_COMMIT_REF_NAME -f Dockerfile.dev -t registry.gitlab.com/fluidsignal/asserts:dev .

lint:
    stage: test
    script:
        - docker-compose run lint
        - docker-compose run overcommit

test:
    stage: test
    script:
        - docker-compose run test

codequality:
  stage: test
  script:
    - docker pull codeclimate/codeclimate
    - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate analyze -e sonar-python -e pep8 -p grep -f json > codeclimate.json
  artifacts:
    paths: [codeclimate.json]

deploy:
    stage: deploy
    script:
        - docker-compose run deploy
        - docker build --no-cache -f Dockerfile.runner -t registry.gitlab.com/fluidsignal/asserts:runner .
    only:
    - master

push_container:
    stage: postdeploy
    script:
        - docker push registry.gitlab.com/fluidsignal/asserts:dev
        - docker tag registry.gitlab.com/fluidsignal/asserts:dev registry.gitlab.com/fluidsignal/asserts:master
        - docker push registry.gitlab.com/fluidsignal/asserts:master
        - docker push registry.gitlab.com/fluidsignal/asserts:base
        - docker push registry.gitlab.com/fluidsignal/asserts:builder
        - docker push registry.gitlab.com/fluidsignal/asserts:runner
    only:
    - master
