image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
    - docker -D login -u $DOCKER_USER -p $DOCKER_PASS
    - docker build -t asserts .

codequality:
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - docker pull codeclimate/codeclimate
    - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate init
    - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate analyze -f json > codeclimate.json
  artifacts:
    paths: [codeclimate.json]

stages:
    - build
    - test
    - deploy

build:
    stage: build
    script:
        - docker run -it -v $(pwd):/usr/src/app asserts scons deps

test:
    stage: test
    script:
        - docker run -it -v $(pwd):/usr/src/app asserts scons dist
        - docker run -it -v $(pwd):/usr/src/app asserts scons self
#        - docker run -it -v $(pwd):/usr/src/app -v /var/run/docker.sock:/var/run/docker.sock asserts scons smoke
#        - docker run -it -v $(pwd):/usr/src/app -v /var/run/docker.sock:/var/run/docker.sock asserts scons test

deploy:
    stage: deploy
    script:
        - echo $VAULT > ~/.vault.txt
        - cp conf/dotpypirc ~/.pypirc
        - ansible-vault --vault-password-file ~/.vault.txt decrypt ~/.pypirc
        - docker run -it -v $(pwd):/usr/src/app -v /var/run/docker.sock:/var/run/docker.sock asserts scons dist
        - twine upload build/dist/*.whl || python setup.py sdist bdist_wheel upload;
        - python src/utils/send_mail.py
    only:
    - master

