image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
    - docker login registry.gitlab.com -u $DOCKER_USER -p $DOCKER_PASS
    - apk update
    - apk upgrade
    - apk add python python-dev py-pip build-base
    - pip install docker-compose

codequality:
  script:
    - docker pull codeclimate/codeclimate
    - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate analyze -e sonar-python -e pep8 -p grep -f json > codeclimate.json
  artifacts:
    paths: [codeclimate.json]

stages:
    - build
    - lint
    - test
    - deploy

build:
    stage: build
    script:
        - docker-compose build
        - docker-compose run deps
        - docker-compose push

lint:
    stage: lint
    script:
        - docker-compose run lint

test:
    stage: test
    script:
        - docker-compose run test

deploy:
    stage: deploy
    script:
        - docker-compose run deploy
    only:
    - master

push_container:
    stage: deploy
    script:
        - docker pull registry.gitlab.com/fluidsignal/asserts:dev
        - docker tag registry.gitlab.com/fluidsignal/asserts:dev registry.gitlab.com/fluidsignal/asserts:master
        - docker push registry.gitlab.com/fluidsignal/asserts:master
    only:
    - master
