---
#
# Archivo de configuracion del servicio de integración continua.
#

version: 2
jobs:
  build:
    working_directory: /tmp/fluid-asserts
    docker:
      - image: ubuntu:14.04
      - image: python:2.7.13
    steps:
      # Deps first
      - run: apt-get -qq update; apt-get -y install git
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get -y install software-properties-common
      - run: sudo apt-add-repository -y ppa:ansible/ansible
      - run: sudo apt-get update
      - run: pip install --upgrade pip setuptools
      - run: docker -D login -u $DOCKER_USER -p $DOCKER_PASS -e $DOCKER_EMAIL
      - run: echo $VAULT > ~/.vault.txt
      - run: sudo apt-get -y install scons ansible ruby
      - run: gem install overcommit
      - run: pip install tox tox-pyenv flake8 pylint yamllint \
                twine setupext-gitversion certifi
      - run: docker -D pull fluidsignal/fluidasserts:container
      - run: scons deps
      - run: cp conf/dotpypirc ~/.pypirc
      - run: ansible-vault --vault-password-file ~/.vault.txt decrypt ~/.pypirc
      - run: scons self
      - run: scons smoke

      # Tests
      - run: scons lint
      - run: overcommit --sign
      - run: overcommit --run
      - run: scons test
      - run: scons dist
      - run: scons doc
      - run: cp build/test/results.* $CIRCLE_TEST_REPORTS
      - run: cp -r build/coverage $CIRCLE_ARTIFACTS
      - run: cp -r build/lint $CIRCLE_ARTIFACTS
      - run: cp -r build/doc $CIRCLE_ARTIFACTS
      - run: cp -r build/dist $CIRCLE_ARTIFACTS
      - run: if [[ $CIRCLE_BRANCH == "master" ]] ; then \
                python setup.py sdist bdist_wheel upload; \
                fi
