---
#
# Archivo de configuracion del servicio de integración continua.
#

version: 2
jobs:
  build:
    working_directory: /tmp/fluid-asserts
    docker:
      - image: ubuntu:14.04
      - image: python:2.7.13
    evironment:
      - USER: root 
    steps:
      # Deps first
      - run: apt-get -qq update; apt-get -y install git
      - checkout
      - run: apt-get -y install python-pip python3-pip curl apt-transport-https
      - run: pip install --upgrade pip setuptools
      - run: echo "deb https://download.docker.com/linux/ubuntu trusty stable" >> /etc/apt/sources.list.d/docker.list
      - run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      - run: apt-get -y purge python-setuptools python3-setuptools python-pip python3-pip
      - run: apt-get update
      - run: apt-get -y install docker-ce python-dev libssl-dev libffi-dev scons python-virtualenv || true
      - run: docker -D login -u $DOCKER_USER -p $DOCKER_PASS -e $DOCKER_EMAIL
      - run: echo $VAULT > ~/.vault.txt
        #- run: gem install overcommit
      - run: pip install -U tox flake8 pylint yamllint \
                twine setupext-gitversion certifi ansible
      - run: docker -D pull fluidsignal/fluidasserts:container
      - run: scons deps
      - run: cp conf/dotpypirc ~/.pypirc
      - run: ansible-vault --vault-password-file ~/.vault.txt decrypt ~/.pypirc
      - run: scons self
      - run: scons smoke

      # Tests
      - run: scons lint
      - run: overcommit --sign
      - run: overcommit --run
      - run: scons test
      - run: scons dist
      - run: scons doc
      - run: cp build/test/results.* $CIRCLE_TEST_REPORTS
      - run: cp -r build/coverage $CIRCLE_ARTIFACTS
      - run: cp -r build/lint $CIRCLE_ARTIFACTS
      - run: cp -r build/doc $CIRCLE_ARTIFACTS
      - run: cp -r build/dist $CIRCLE_ARTIFACTS
      - run: if [[ $CIRCLE_BRANCH == "master" ]] ; then \
                python setup.py sdist bdist_wheel upload; \
                fi
