---
version: '3'
services:
  deps:
    build:
      context: .
      dockerfile: Dockerfile.builder
      args:
        gituser: $DOCKER_USER
        gitpass: $DOCKER_PASS
        branch: $CI_COMMIT_SHA
    network_mode: bridge
    tty: true
    command: scons deps
    container_name: asserts
    image: registry.gitlab.com/fluidsignal/asserts:builder
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp${CI_PROJECT_DIR}/${CI_COMMIT_SHA}/src:/usr/src/asserts
    environment:
      - PYPI_USER=$PYPI_USER
      - PYPI_PASS=$PYPI_PASS
      - DOCKER_USER=$DOCKER_USER
      - DOCKER_PASS=$DOCKER_PASS
      - CI_COMMIT_REF_NAME=$CI_COMMIT_REF_NAME

  lint:
    image: registry.gitlab.com/fluidsignal/asserts:builder
    depends_on:
      - deps
    network_mode: bridge
    tty: true
    command: scons lint
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp${CI_PROJECT_DIR}/${CI_COMMIT_SHA}/src:/usr/src/asserts
    environment:
      - PYPI_USER=$PYPI_USER
      - PYPI_PASS=$PYPI_PASS
      - DOCKER_USER=$DOCKER_USER
      - DOCKER_PASS=$DOCKER_PASS
      - CI_COMMIT_REF_NAME=$CI_COMMIT_REF_NAME

  overcommit:
    image: registry.gitlab.com/fluidsignal/asserts:builder
    depends_on:
      - deps
    network_mode: bridge
    tty: true
    command: >
      bash -c "overcommit -s && overcommit -s pre-commit && overcommit -r"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp${CI_PROJECT_DIR}/${CI_COMMIT_SHA}/src:/usr/src/asserts
    environment:
      - PYPI_USER=$PYPI_USER
      - PYPI_PASS=$PYPI_PASS
      - DOCKER_USER=$DOCKER_USER
      - DOCKER_PASS=$DOCKER_PASS
      - CI_COMMIT_REF_NAME=$CI_COMMIT_REF_NAME

  bandit:
    image: registry.gitlab.com/fluidsignal/asserts:builder
    depends_on:
      - deps
    network_mode: bridge
    tty: true
    command: scons bandit
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp${CI_PROJECT_DIR}/${CI_COMMIT_SHA}/src:/usr/src/asserts
    environment:
      - PYPI_USER=$PYPI_USER
      - PYPI_PASS=$PYPI_PASS
      - DOCKER_USER=$DOCKER_USER
      - DOCKER_PASS=$DOCKER_PASS
      - CI_COMMIT_REF_NAME=$CI_COMMIT_REF_NAME

  dist:
    image: registry.gitlab.com/fluidsignal/asserts:builder
    depends_on:
      - deps
    network_mode: bridge
    tty: true
    command: scons dist
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp${CI_PROJECT_DIR}/${CI_COMMIT_SHA}/src:/usr/src/asserts
    environment:
      - PYPI_USER=$PYPI_USER
      - PYPI_PASS=$PYPI_PASS
      - DOCKER_USER=$DOCKER_USER
      - DOCKER_PASS=$DOCKER_PASS
      - CI_COMMIT_REF_NAME=$CI_COMMIT_REF_NAME

  test:
    image: registry.gitlab.com/fluidsignal/asserts:builder
    depends_on:
      - deps
    network_mode: bridge
    tty: true
    command: scons test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp${CI_PROJECT_DIR}/${CI_COMMIT_SHA}/src:/usr/src/asserts
    environment:
      - PYPI_USER=$PYPI_USER
      - PYPI_PASS=$PYPI_PASS
      - DOCKER_USER=$DOCKER_USER
      - DOCKER_PASS=$DOCKER_PASS
      - CI_COMMIT_REF_NAME=$CI_COMMIT_REF_NAME

  deploy:
    image: registry.gitlab.com/fluidsignal/asserts:builder
    depends_on:
      - deps
      - dist
    network_mode: bridge
    tty: true
    command: scons deploy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp${CI_PROJECT_DIR}/${CI_COMMIT_SHA}/src:/usr/src/asserts
    environment:
      - PYPI_USER=$PYPI_USER
      - PYPI_PASS=$PYPI_PASS
      - DOCKER_USER=$DOCKER_USER
      - DOCKER_PASS=$DOCKER_PASS
      - MANDRILL_APIKEY=$MANDRILL_APIKEY
      - CI_COMMIT_REF_NAME=$CI_COMMIT_REF_NAME
