version: '3'
services:
  deps:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        gituser: $DOCKER_USER
        gitpass: $DOCKER_PASS
        branch: $CI_COMMIT_REF_NAME
    command: scons deps
    container_name: asserts
    image: registry.gitlab.com/fluidsignal/asserts:dev
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
     - VAULT=$VAULT
     - FLUIDASSERTS_LICENSE_KEY=$FLUIDASSERTS_LICENSE_KEY
     - FLUIDASSERTS_USER_EMAIL=$FLUIDASSERTS_USER_EMAIL
     - DOCKER_USER=$DOCKER_USER
     - DOCKER_PASS=$DOCKER_PASS

  self:
    image: registry.gitlab.com/fluidsignal/asserts:dev
    depends_on:
     - deps
    command: scons self
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
     - VAULT=$VAULT
     - FLUIDASSERTS_LICENSE_KEY=$FLUIDASSERTS_LICENSE_KEY
     - FLUIDASSERTS_USER_EMAIL=$FLUIDASSERTS_USER_EMAIL
     - DOCKER_USER=$DOCKER_USER
     - DOCKER_PASS=$DOCKER_PASS

  lint:
    image: registry.gitlab.com/fluidsignal/asserts:dev
    depends_on:
     - deps
    command: scons lint
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
     - VAULT=$VAULT
     - FLUIDASSERTS_LICENSE_KEY=$FLUIDASSERTS_LICENSE_KEY
     - FLUIDASSERTS_USER_EMAIL=$FLUIDASSERTS_USER_EMAIL
     - DOCKER_USER=$DOCKER_USER
     - DOCKER_PASS=$DOCKER_PASS

  dist:
    image: registry.gitlab.com/fluidsignal/asserts:dev
    depends_on:
     - deps
    command: scons dist
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
     - VAULT=$VAULT
     - FLUIDASSERTS_LICENSE_KEY=$FLUIDASSERTS_LICENSE_KEY
     - FLUIDASSERTS_USER_EMAIL=$FLUIDASSERTS_USER_EMAIL
     - DOCKER_USER=$DOCKER_USER
     - DOCKER_PASS=$DOCKER_PASS

  test:
    image: registry.gitlab.com/fluidsignal/asserts:dev
    depends_on:
     - deps
     - dist
    command: scons test
    networks:
     - fluidasserts
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
     - VAULT=$VAULT
     - FLUIDASSERTS_LICENSE_KEY=$FLUIDASSERTS_LICENSE_KEY
     - FLUIDASSERTS_USER_EMAIL=$FLUIDASSERTS_USER_EMAIL
     - DOCKER_USER=$DOCKER_USER
     - DOCKER_PASS=$DOCKER_PASS

  deploy:
    image: registry.gitlab.com/fluidsignal/asserts:dev
    depends_on:
     - deps
     - dist
    command: scons deploy
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
     - VAULT=$VAULT
     - FLUIDASSERTS_LICENSE_KEY=$FLUIDASSERTS_LICENSE_KEY
     - FLUIDASSERTS_USER_EMAIL=$FLUIDASSERTS_USER_EMAIL
     - DOCKER_USER=$DOCKER_USER
     - DOCKER_PASS=$DOCKER_PASS

networks:
  fluidasserts:
    ipam:
      config:
        - subnet: 172.30.216.0/24
