version: '3'
services:
  deps:
    build: .
    command: scons deps
    container_name: asserts
    image: registry.gitlab.com/fluidsignal/asserts:dev
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
     - VAULT=$VAULT
     - FLUIDASSERTS_LICENSE_KEY=$FLUIDASSERTS_LICENSE_KEY
     - FLUIDASSERTS_USER_EMAIL=$FLUIDASSERTS_USER_EMAIL

  self:
    image: registry.gitlab.com/fluidsignal/asserts:dev
    depends_on:
     - deps
    command: scons self
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
     - VAULT=$VAULT
     - FLUIDASSERTS_LICENSE_KEY=$FLUIDASSERTS_LICENSE_KEY
     - FLUIDASSERTS_USER_EMAIL=$FLUIDASSERTS_USER_EMAIL

  lint:
    image: registry.gitlab.com/fluidsignal/asserts:dev
    depends_on:
     - deps
    command: scons lint
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
     - VAULT=$VAULT
     - FLUIDASSERTS_LICENSE_KEY=$FLUIDASSERTS_LICENSE_KEY
     - FLUIDASSERTS_USER_EMAIL=$FLUIDASSERTS_USER_EMAIL

  dist:
    image: registry.gitlab.com/fluidsignal/asserts:dev
    depends_on:
     - deps
    command: scons dist
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
     - VAULT=$VAULT
     - FLUIDASSERTS_LICENSE_KEY=$FLUIDASSERTS_LICENSE_KEY
     - FLUIDASSERTS_USER_EMAIL=$FLUIDASSERTS_USER_EMAIL

  test:
    image: registry.gitlab.com/fluidsignal/asserts:dev
    depends_on:
     - deps
     - dist
    command: scons test
    networks:
     - fluidasserts
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
     - VAULT=$VAULT
     - FLUIDASSERTS_LICENSE_KEY=$FLUIDASSERTS_LICENSE_KEY
     - FLUIDASSERTS_USER_EMAIL=$FLUIDASSERTS_USER_EMAIL

  deploy:
    image: registry.gitlab.com/fluidsignal/asserts:dev
    depends_on:
     - deps
     - dist
    command: scons deploy
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
     - VAULT=$VAULT
     - FLUIDASSERTS_LICENSE_KEY=$FLUIDASSERTS_LICENSE_KEY
     - FLUIDASSERTS_USER_EMAIL=$FLUIDASSERTS_USER_EMAIL

networks:
  fluidasserts:
    ipam:
      config:
        - subnet: 172.30.216.0/24
