---
version: '3'
services:
  deps:
    build:
      context: .
      dockerfile: Dockerfile.builder
      args:
        gituser: $DOCKER_USER
        gitpass: $DOCKER_PASS
        branch: $CI_COMMIT_SHA
    command: scons deps
    container_name: asserts
    image: registry.gitlab.com/fluidsignal/asserts:builder
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp${CI_PROJECT_DIR}/${CI_COMMIT_SHA}/src:/usr/src/asserts
    environment:
      - PYPI_USER=$PYPI_USER
      - PYPI_PASS=$PYPI_PASS
      - DOCKER_USER=$DOCKER_USER
      - DOCKER_PASS=$DOCKER_PASS

  self:
    image: registry.gitlab.com/fluidsignal/asserts:builder
    depends_on:
      - deps
    command: scons self
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp${CI_PROJECT_DIR}/${CI_COMMIT_SHA}/src:/usr/src/asserts
    environment:
      - PYPI_USER=$PYPI_USER
      - PYPI_PASS=$PYPI_PASS
      - DOCKER_USER=$DOCKER_USER
      - DOCKER_PASS=$DOCKER_PASS

  lint:
    image: registry.gitlab.com/fluidsignal/asserts:builder
    depends_on:
      - deps
    command: scons lint
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp${CI_PROJECT_DIR}/${CI_COMMIT_SHA}/src:/usr/src/asserts
    environment:
      - PYPI_USER=$PYPI_USER
      - PYPI_PASS=$PYPI_PASS
      - DOCKER_USER=$DOCKER_USER
      - DOCKER_PASS=$DOCKER_PASS

  overcommit:
    image: registry.gitlab.com/fluidsignal/asserts:builder
    depends_on:
      - deps
    command: >
      bash -c "overcommit -s && overcommit -s pre-commit && overcommit -r"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp${CI_PROJECT_DIR}/${CI_COMMIT_SHA}/src:/usr/src/asserts
    environment:
      - PYPI_USER=$PYPI_USER
      - PYPI_PASS=$PYPI_PASS
      - DOCKER_USER=$DOCKER_USER
      - DOCKER_PASS=$DOCKER_PASS

  dist:
    image: registry.gitlab.com/fluidsignal/asserts:builder
    depends_on:
      - deps
    command: scons dist
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp${CI_PROJECT_DIR}/${CI_COMMIT_SHA}/src:/usr/src/asserts
    environment:
      - PYPI_USER=$PYPI_USER
      - PYPI_PASS=$PYPI_PASS
      - DOCKER_USER=$DOCKER_USER
      - DOCKER_PASS=$DOCKER_PASS

  test:
    image: registry.gitlab.com/fluidsignal/asserts:builder
    depends_on:
      - deps
    command: scons test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp${CI_PROJECT_DIR}/${CI_COMMIT_SHA}/src:/usr/src/asserts
    environment:
      - PYPI_USER=$PYPI_USER
      - PYPI_PASS=$PYPI_PASS
      - DOCKER_USER=$DOCKER_USER
      - DOCKER_PASS=$DOCKER_PASS

  deploy:
    image: registry.gitlab.com/fluidsignal/asserts:builder
    depends_on:
      - deps
      - dist
    command: scons deploy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp${CI_PROJECT_DIR}/${CI_COMMIT_SHA}/src:/usr/src/asserts
    environment:
      - PYPI_USER=$PYPI_USER
      - PYPI_PASS=$PYPI_PASS
      - DOCKER_USER=$DOCKER_USER
      - DOCKER_PASS=$DOCKER_PASS
